spring:
  application:
    name: spring-lens
  ai:
    openai:
      api-key: ${GROQ_AI_API_KEY}
      groq-url: https://api.groq.com/openai/v1/chat/completions
      base-url: https://api.groq.com/openai
      chat:
        options:
          model: llama-3.3-70b-versatile
      embedding:
        api-key: ${OPENAI_API_KEY}
        base-url: https://api.openai.com
        options:
          model: text-embedding-3-small
    vectorstore:
      pgvector:
        initialize-schema: true
        dimensions: 1536
        distance-type: COSINE_DISTANCE
  datasource:
    url: jdbc:postgresql://localhost:5432/springlens
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

  webflux:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: 8087

resilience4j:
  circuitbreaker:
    instances:
      groqClient:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3

springlens:
  ingestion:
    chunk-size: 512
    min-chunk-size-chars: 50
    min-chunk-length-to-embed: 5
    max-num-chunks: 10000
    keep-separator: true
    similarity-threshold: 0.5
    top-k: 4
    pdf-reader-type: auto


logging:
  level:
    root: INFO
    com.ai.spring_lens: DEBUG
    org.springframework.ai.vectorstore.pgvector.PgVectorStore: DEBUG
    org.springframework.ai.openai.OpenAiEmbeddingModel: DEBUG
    org.springframework.ai.openai.OpenAiChatModel: DEBUG
    org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG
    org.springframework.ai.transformer.splitter: DEBUG
    org.springframework.ai.reader: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/spring-lens.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7
      file-name-pattern: logs/spring-lens-%d{yyyy-MM-dd}.%i.log

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always